# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccodolo" do
  version "0.7.0"

  on_macos do
    url "https://github.com/skwashd/ccodolo/releases/download/v#{version}/ccodolo_#{version}_darwin_all.tar.gz"
    sha256 "6c3a9c13c0c02f68b418c7eba1596dd5d794f26228aa9e38488f6160c43bc7a2"
  end

  on_linux do
    on_intel do
      url "https://github.com/skwashd/ccodolo/releases/download/v#{version}/ccodolo_#{version}_linux_amd64.tar.gz"
      sha256 "08188ec757ce1d756767eab16d22fe33c4b20c4d2b5e43374e775a75191e331b"
    end
    on_arm do
      url "https://github.com/skwashd/ccodolo/releases/download/v#{version}/ccodolo_#{version}_linux_arm64.tar.gz"
      sha256 "6fd12c7ae415e6e4e28480bd6735e0d3e178a8927ecbbfc8df19924a491e2bd0"
    end
  end

  name "ccodolo"
  desc "Sandboxed Docker containers for running AI coding assistants in YOLO mode"
  homepage "https://github.com/skwashd/ccodolo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccodolo"

  # No zap stanza required

end
