# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccodolo" do
  version "0.5.4"

  on_macos do
    url "https://github.com/skwashd/ccodolo/releases/download/v#{version}/ccodolo_#{version}_darwin_all.tar.gz"
    sha256 "bd6e35e79425a0458311a7940c59eead7920fba1a25988a215d7cffb742898b7"
  end

  on_linux do
    on_intel do
      url "https://github.com/skwashd/ccodolo/releases/download/v#{version}/ccodolo_#{version}_linux_amd64.tar.gz"
      sha256 "f0f1c9d34f4da312ec0c75828e5650ac2c9692e29898c96050fbb5e1b682d3f9"
    end
    on_arm do
      url "https://github.com/skwashd/ccodolo/releases/download/v#{version}/ccodolo_#{version}_linux_arm64.tar.gz"
      sha256 "defd83843a271682ffaeb865b28bd53fa17eab3e979be3fdd6ac81b3eb0ddc81"
    end
  end

  name "ccodolo"
  desc "Sandboxed Docker containers for running AI coding assistants in YOLO mode"
  homepage "https://github.com/skwashd/ccodolo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccodolo"

  # No zap stanza required

end
