# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccodolo" do
  version "0.5.1"

  on_macos do
    url "https://github.com/skwashd/ccodolo/releases/download/v#{version}/ccodolo_#{version}_darwin_all.tar.gz"
    sha256 "4b2a67673b408ef76799bdc0012154dc5e0e3f716d0c3ba067c24fbde893a7e2"
  end

  on_linux do
    on_intel do
      url "https://github.com/skwashd/ccodolo/releases/download/v#{version}/ccodolo_#{version}_linux_amd64.tar.gz"
      sha256 "7028e7f78be6b24e9525f215a390ea9520c952e133159b613a08a80299170d16"
    end
    on_arm do
      url "https://github.com/skwashd/ccodolo/releases/download/v#{version}/ccodolo_#{version}_linux_arm64.tar.gz"
      sha256 "778fcc9821f1a260b4c056c0b98272bfeb69877fcdddbc850e84f4f577653ac0"
    end
  end

  name "ccodolo"
  desc "Sandboxed Docker containers for running AI coding assistants in YOLO mode"
  homepage "https://github.com/skwashd/ccodolo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccodolo"

  # No zap stanza required

end
